apiVersion: apps/v1
kind: Deployment
metadata:
  name: back # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: dev
  template:
    metadata:
      labels:
        environment: dev
    spec:
      containers:
        - name: breaking-news-back-app
          image: deemp/breaking-news-back-app:latest # Sets Image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # Exposes container port
              name: back-port
          env:
            - name: CONFIG_FILE
              value: /etc/config/back.yaml
            - name: JWK_FILE
              value: /etc/jwk/jwk.yaml
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
            - mountPath: /etc/jwk
              name: jwk-volume
          # command: [ "/bin/sh", "-c", "ls /etc/config" ]
      volumes:
        - name: config-volume
          configMap:
            name: back-config
        - name: jwk-volume
          configMap:
            name: jwk-config
---
apiVersion: v1
kind: Service
metadata:
  name: back # Sets service name
  labels:
    environment: dev # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 8081 # Sets port to run the service
      name: back-service-port
      targetPort: back-port
      nodePort: 30007
  selector:
    environment: dev
