name: back-end
version: 0.1.0.0
github: "value/back-end"
license: BSD3
author: "value"
maintainer: "value"
copyright: "value"

# extra-source-files: {}

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/value/back-end#readme>

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - GADTs
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - NamedFieldPuns
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - wai
  - string-interpolate

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - aeson
    - async
    - bytestring
    - containers
    - effectful
    - effectful-th
    - esqueleto
    - exceptions
    - filepath
    - hashable
    - lens
    - monad-logger
    - monad-logger-aeson
    - mtl
    - openapi3
    - persistent
    - persistent-postgresql
    - resource-pool
    - servant
    - servant-client
    - servant-docs
    - servant-openapi3
    - servant-server
    - template-haskell
    - text
    - time
    - transformers
    - warp
    - yaml
    - data-default

executables:
  back-end:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - back-end
  gen-oas3:
    main: GenerateOpenAPI3.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - back-end
