name: back
version: 0.1.0.0
github: "value/back"
license: BSD3
author: "value"
maintainer: "value"
copyright: "value"

# extra-source-files: {}

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/value/back#readme>

default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - ImplicitParams
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - wai
  - string-interpolate
  - effectful-core
  - effectful-plugin

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fplugin=Effectful.Plugin

library:
  source-dirs: src
  dependencies:
    - aeson
    - async
    - bytestring
    - containers
    - data-default
    - effectful
    - effectful-th
    - esqueleto
    - exceptions
    - filepath
    - hashable
    - lens
    - monad-logger
    - monad-logger-aeson
    - mtl
    - openapi3
    - persistent
    - persistent-postgresql
    - resource-pool
    - servant
    - servant-client
    - servant-docs
    - servant-openapi3
    - servant-server
    - template-haskell
    - text
    - time
    - transformers
    - warp
    - yaml
    - servant-auth-server
    - servant-auth
    - jose
    - insert-ordered-containers
    - http-api-data
    - servant-queryparam-server
    - servant-queryparam-core
    - first-class-families
    - symbols
    - generic-lens
    - stm-containers

executables:
  back:
    main: Main.hs
    source-dirs: app/Server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - back
  gen-openapi3:
    main: Main.hs
    source-dirs: app/GenerateOpenAPI3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - back
