
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app }}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: copy_database
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - "pg_dump {{ .Values.db1 }} | psql {{ .Values.db2 }}"
          restartPolicy: OnFailure
