name: back-end
version: 0.1.0.0
github: "value/back-end"
license: BSD3
author: "value"
maintainer: "value"
copyright: "value"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/value/back-end#readme>

default-extensions:
  - ImportQualifiedPost
  - LambdaCase
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ConstraintKinds
  - OverloadedStrings
  - RankNTypes

dependencies:
  - base >= 4.7 && < 5
  - time
  - yaml
  - aeson
  - async
  - bytestring
  - exceptions
  - filepath
  - servant
  - servant-client
  - servant-docs
  - servant-server
  - wai
  - warp
  - text
  - hashable
  - effectful
  - effectful-th
  - monad-logger-aeson
  - lens
  - mtl
  - monad-logger
  - transformers
  - resource-pool
  - persistent
  - persistent-postgresql
  - esqueleto

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  back-end:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - back-end

tests:
  back-end-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - back-end
