components:
  schemas:
    CreateNews:
      properties:
        category:
          type: string
        images:
          items:
            $ref: '#/components/schemas/IndexedImage'
          type: array
        text:
          type: string
        title:
          type: string
      required:
      - title
      - text
      - category
      - images
      type: object
    GetNews:
      properties:
        category:
          type: string
        id:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
        images:
          items:
            $ref: '#/components/schemas/IndexedImage'
          type: array
        text:
          type: string
      required:
      - id
      - text
      - category
      - images
      type: object
    IndexedImage:
      properties:
        id:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
        value:
          type: string
      required:
      - id
      - value
      type: object
    UTCTime:
      example: 2016-07-22T00:00:00Z
      format: yyyy-mm-ddThh:MM:ssZ
      type: string
    UserRegistrationForm:
      properties:
        email:
          type: string
        password:
          type: string
      required:
      - email
      - password
      type: object
info:
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/user:
    post:
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/UserRegistrationForm'
      responses:
        '200':
          content:
            application/json;charset=utf-8: {}
          description: ''
        '400':
          description: Invalid `body`
  /api1/news/create:
    put:
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/CreateNews'
      responses:
        '200':
          content:
            application/json;charset=utf-8: {}
          description: ''
        '400':
          description: Invalid `body`
  /api1/news/get:
    put:
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/UTCTime'
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                items:
                  $ref: '#/components/schemas/GetNews'
                type: array
          description: ''
        '400':
          description: Invalid `body`
