components:
  schemas:
    AuthorName:
      type: string
    CategoryId:
      maximum: 9223372036854775807
      minimum: -9223372036854775808
      type: integer
    CreateNews:
      properties:
        category:
          $ref: '#/components/schemas/CategoryId'
        images:
          items:
            $ref: '#/components/schemas/Image'
          type: array
        text:
          $ref: '#/components/schemas/NewsText'
        title:
          $ref: '#/components/schemas/Title'
      required:
      - title
      - text
      - category
      - images
      type: object
    CreatedAt:
      example: 2016-07-22T00:00:00Z
      format: yyyy-mm-ddThh:MM:ssZ
      type: string
    Either_LoginError_FullToken:
      oneOf:
      - properties:
          Left:
            $ref: '#/components/schemas/LoginError'
        required:
        - Left
        type: object
      - properties:
          Right:
            $ref: '#/components/schemas/FullToken'
        required:
        - Right
        type: object
    Either_RegisterError_FullToken:
      oneOf:
      - properties:
          Left:
            $ref: '#/components/schemas/RegisterError'
        required:
        - Left
        type: object
      - properties:
          Right:
            $ref: '#/components/schemas/FullToken'
        required:
        - Right
        type: object
    Either_RotateError_FullToken:
      oneOf:
      - properties:
          Left:
            $ref: '#/components/schemas/RotateError'
        required:
        - Left
        type: object
      - properties:
          Right:
            $ref: '#/components/schemas/FullToken'
        required:
        - Right
        type: object
    FullToken:
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
      - refreshToken
      - accessToken
      type: object
    GetNews:
      properties:
        authorName:
          $ref: '#/components/schemas/AuthorName'
        category:
          $ref: '#/components/schemas/CategoryId'
        createdAt:
          $ref: '#/components/schemas/CreatedAt'
        images:
          items:
            $ref: '#/components/schemas/Image'
          type: array
        isPublished:
          type: boolean
        text:
          $ref: '#/components/schemas/NewsText'
        title:
          $ref: '#/components/schemas/Title'
      required:
      - title
      - createdAt
      - authorName
      - category
      - text
      - images
      - isPublished
      type: object
    Image:
      type: string
    LoginError:
      enum:
      - UserDoesNotExist
      type: string
    NewsText:
      type: string
    Password:
      type: string
    RegisterError:
      enum:
      - UserExists
      type: string
    RotateError:
      enum:
      - SessionDoesNotExist
      - SessionHasNewerRefreshTokenId
      type: string
    Title:
      type: string
    UserLoginForm:
      properties:
        password:
          $ref: '#/components/schemas/Password'
        userName:
          $ref: '#/components/schemas/UserName'
      required:
      - userName
      - password
      type: object
    UserName:
      type: string
    UserRegisterForm:
      properties:
        authorName:
          $ref: '#/components/schemas/AuthorName'
        password:
          $ref: '#/components/schemas/Password'
        userName:
          $ref: '#/components/schemas/UserName'
      required:
      - userName
      - password
      - authorName
      type: object
  securitySchemes:
    JWT:
      bearerFormat: JWT
      description: Bearer Authentication
      scheme: bearer
      type: http
info:
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api1/news/create:
    post:
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/CreateNews'
      responses:
        '200':
          content:
            application/json;charset=utf-8: {}
          description: ''
        '400':
          description: Invalid `body`
      security:
      - JWT: []
  /api1/news/get:
    get:
      parameters:
      - in: query
        name: createdUntil
        required: false
        schema:
          format: yyyy-mm-ddThh:MM:ssZ
          type: string
      - in: query
        name: createdSince
        required: false
        schema:
          format: yyyy-mm-ddThh:MM:ssZ
          type: string
      - in: query
        name: createdAt
        required: false
        schema:
          format: yyyy-mm-ddThh:MM:ssZ
          type: string
      - in: query
        name: authorName
        required: false
        schema:
          type: string
      - in: query
        name: category
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      - in: query
        name: titleLike
        required: false
        schema:
          type: string
      - in: query
        name: textLike
        required: false
        schema:
          type: string
      - in: query
        name: block
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                items:
                  $ref: '#/components/schemas/GetNews'
                type: array
          description: ''
        '400':
          description: Invalid `block` or `textLike` or `titleLike` or `category`
            or `authorName` or `createdAt` or `createdSince` or `createdUntil`
      security:
      - JWT: []
  /api1/user/login:
    post:
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/UserLoginForm'
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Either_LoginError_FullToken'
          description: ''
        '400':
          description: Invalid `body`
  /api1/user/register:
    post:
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/UserRegisterForm'
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Either_RegisterError_FullToken'
          description: ''
        '400':
          description: Invalid `body`
  /api1/user/rotate-refresh-token:
    post:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Either_RotateError_FullToken'
          description: ''
      security:
      - JWT: []
